const fakeData = [
  { user_id: 1,
  display_name: 'A_Seagull',
  logo: 'https://static-cdn.jtvnw.net/jtv_user_pictures/a_seagull-profile_image-4d2d235688c7dc66-70x70.png',
  profile_image_url: 'https://static-cdn.jtvnw.net/jtv_user_pictures/da9d954d-8759-4325-a1ca-46d58c43c93d-profile_banner-480.png',
  category: 'Overwatch',
  followers: 906030,
  following: 194 },
{ user_id: 2,
  display_name: 't3nwinter',
  logo: 'https://static-cdn.jtvnw.net/jtv_user_pictures/790a3de34cfd5032-profile_image-70x70.jpeg',
  profile_image_url: ' http://lorempixel.com/640/480/sports',
  category: 'Overwatch',
  followers: 98566,
  following: 19850 },
{ user_id: 3,
  display_name: 'chiquita_bananna',
  logo: 'https://static-cdn.jtvnw.net/jtv_user_pictures/b962fca7-d547-4be7-8570-31cf83960e53-profile_image-70x70.png',
  profile_image_url: ' http://lorempixel.com/640/480/city',
  category: 'Overwatch',
  followers: 80141,
  following: 3833 },
{ user_id: 4,
  display_name: 'EllieP',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/clubb3rry/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/people',
  category: 'League of Legends',
  followers: 92576,
  following: 57086 },
{ user_id: 5,
  display_name: 'lonnidbra8545',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/prrstn/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/business',
  category: 'FIFA 19',
  followers: 87941,
  following: 78769 },
{ user_id: 6,
  display_name: 'on1y_on1xxxxx',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/instalox/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/nature',
  category: 'Dota 2',
  followers: 29472,
  following: 9306 },
{ user_id: 7,
  display_name: 'Im_Looping',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/haligaliharun/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/business',
  category: 'Minecraft',
  followers: 19789,
  following: 85305 },
{ user_id: 8,
  display_name: 'xry0d3nn',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/ernestsemerda/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/city',
  category: 'Portal 2',
  followers: 96444,
  following: 8016 },
{ user_id: 9,
  display_name: 'tiktok08',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/ismail_biltagi/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/people',
  category: 'Counter-Strike: Global Offensive',
  followers: 10119,
  following: 61496 },
{ user_id: 10,
  display_name: 'p1nkyMoon',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/turkutuuli/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/nightlife',
  category: 'Counter-Strike: Global Offensive',
  followers: 96592,
  following: 63923 },
{ user_id: 11,
  display_name: 'ThatVicctor',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/dawidwu/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/animals',
  category: 'Left 4 Dead 2',
  followers: 43938,
  following: 39396 },
{ user_id: 12,
  display_name: 'beverlymdztqw698',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/hjartstrorn/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/transport',
  category: 'Sea of Thieves',
  followers: 89557,
  following: 82776 },
{ user_id: 13,
  display_name: 'MarketDown',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/baumann_alex/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/transport',
  category: 'Dota 2',
  followers: 25767,
  following: 6200 },
{ user_id: 14,
  display_name: 'louieareno',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/Chakintosh/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/business',
  category: 'Call of Duty: Black Ops 4',
  followers: 69596,
  following: 49514 },
{ user_id: 15,
  display_name: 'project_jj',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/vladarbatov/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/abstract',
  category: 'League of Legends',
  followers: 90561,
  following: 84513 },
{ user_id: 16,
  display_name: 'salvatore_____',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/twittypork/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/cats',
  category: 'Counter-Strike: Global Offensive',
  followers: 19128,
  following: 79540 },
{ user_id: 17,
  display_name: 'ali3nog',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/supjoey/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/people',
  category: 'League of Legends',
  followers: 64204,
  following: 77861 },
{ user_id: 18,
  display_name: 'Tiernix',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/christianoliff/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/abstract',
  category: 'Just Chatting',
  followers: 81293,
  following: 37459 },
{ user_id: 19,
  display_name: 'neon_8231',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/mr_subtle/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/people',
  category: 'Grand Theft Auto V',
  followers: 3698,
  following: 40169 },
{ user_id: 20,
  display_name: 'andresss_96',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/emsgulam/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/people',
  category: 'Magic: The Gathering',
  followers: 11391,
  following: 70239 },
{ user_id: 21,
  display_name: 'sekaovjjy24',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/drewbyreese/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/transport',
  category: 'Dota 2',
  followers: 16474,
  following: 61520 },
{ user_id: 22,
  display_name: 'SirKraider',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/vocino/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/business',
  category: 'PLAYERUNKNOWN\'S BATTLEGROUNDS',
  followers: 37359,
  following: 53716 },
{ user_id: 23,
  display_name: 'kirk2741',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/ma_tiax/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/food',
  category: 'Dota 2',
  followers: 89501,
  following: 12759 },
{ user_id: 24,
  display_name: 'nala_n_pepper2',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/surgeonist/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/cats',
  category: 'Call of Duty: Black Ops 4',
  followers: 31842,
  following: 31558 },
{ user_id: 25,
  display_name: 'javierR20',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/louis_currie/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/technics',
  category: 'Fortnite',
  followers: 850,
  following: 74284 },
{ user_id: 26,
  display_name: 'OIigarchas_',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/danthms/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/abstract',
  category: 'Rocket League',
  followers: 23469,
  following: 93032 },
{ user_id: 27,
  display_name: 'kyiomin',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/pehamondello/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/people',
  category: 'Counter-Strike: Global Offensive',
  followers: 27554,
  following: 44969 },
{ user_id: 28,
  display_name: 'qlebberoni',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/michigangraham/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/city',
  category: 'Overwatch',
  followers: 54288,
  following: 63975 },
{ user_id: 29,
  display_name: 'MoneyMonkey222',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/lvovenok/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/nightlife',
  category: 'Super Smash Bros. Ultimate',
  followers: 8205,
  following: 42643 },
{ user_id: 30,
  display_name: 'PineappleChapel',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/beweinreich/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/fashion',
  category: 'Left 4 Dead 2',
  followers: 61465,
  following: 20882 },
{ user_id: 31,
  display_name: 'Doopules',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/kerem/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/fashion',
  category: 'Hearthstone',
  followers: 3239,
  following: 76349 },
{ user_id: 32,
  display_name: 'FrostBud',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/m_kalibry/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/cats',
  category: 'League of Legends',
  followers: 69727,
  following: 19290 },
{ user_id: 33,
  display_name: 'Chanpuruu',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/shojberg/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/sports',
  category: 'StarCraft II',
  followers: 47973,
  following: 43986 },
{ user_id: 34,
  display_name: 'strowygos',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/zauerkraut/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/business',
  category: 'League of Legends',
  followers: 97751,
  following: 3337 },
{ user_id: 35,
  display_name: 'smtxzzz',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/arthurholcombe1/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/people',
  category: 'Sea of Thieves',
  followers: 55685,
  following: 207 },
{ user_id: 36,
  display_name: 'kingyurbaby',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/marcobarbosa/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/business',
  category: 'Call of Duty: Black Ops 4',
  followers: 51300,
  following: 71887 },
{ user_id: 37,
  display_name: 'CowBoyGamer11',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/chris_frees/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/city',
  category: 'PLAYERUNKNOWN\'S BATTLEGROUNDS',
  followers: 65811,
  following: 37389 },
{ user_id: 38,
  display_name: 'VakSparrow',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/stushona/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/cats',
  category: 'Counter-Strike: Global Offensive',
  followers: 96699,
  following: 9104 },
{ user_id: 39,
  display_name: 'Kitnxknight',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/ricburton/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/technics',
  category: 'Super Smash Bros. Ultimate',
  followers: 34938,
  following: 83036 },
{ user_id: 40,
  display_name: 'z3usowskyyy',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/agromov/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/technics',
  category: 'Hearthstone',
  followers: 45853,
  following: 98476 },
{ user_id: 41,
  display_name: 'rheaewlq7704',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/malgordon/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/cats',
  category: 'Grand Theft Auto V',
  followers: 17127,
  following: 78120 },
{ user_id: 42,
  display_name: 'Dotiing',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/mymyboy/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/people',
  category: 'Grand Theft Auto V',
  followers: 64990,
  following: 40683 },
{ user_id: 43,
  display_name: 'gabbeyuhyt5628',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/adhamdannaway/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/city',
  category: 'League of Legends',
  followers: 82358,
  following: 80512 },
{ user_id: 44,
  display_name: 'beatriceajfgb4648',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/_kkga/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/nature',
  category: 'World of Warcraft',
  followers: 65803,
  following: 98873 },
{ user_id: 45,
  display_name: 'Enroo2',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/cbracco/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/nature',
  category: 'Rocket League',
  followers: 82471,
  following: 10595 },
{ user_id: 46,
  display_name: 'tatemorrison',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/olaolusoga/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/abstract',
  category: 'StarCraft II',
  followers: 24344,
  following: 78392 },
{ user_id: 47,
  display_name: 'faithdfja93',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/ahmetsulek/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/transport',
  category: 'StarCraft II',
  followers: 69772,
  following: 9543 },
{ user_id: 48,
  display_name: 'dixrzsmyo',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/ariffsetiawan/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/business',
  category: 'Dota 2',
  followers: 68408,
  following: 61624 },
{ user_id: 49,
  display_name: 'deancody',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/edgarchris99/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/technics',
  category: 'Counter-Strike: Global Offensive',
  followers: 67626,
  following: 1534 },
{ user_id: 50,
  display_name: 'mrjackdanielz',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/mcflydesign/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/business',
  category: 'StarCraft II',
  followers: 95830,
  following: 52023 },
{ user_id: 51,
  display_name: 'rjunie',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/ripplemdk/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/food',
  category: 'StarCraft II',
  followers: 46310,
  following: 79260 },
{ user_id: 52,
  display_name: 'ruthybrcvw922',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/joemdesign/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/business',
  category: 'StarCraft II',
  followers: 21086,
  following: 96162 },
{ user_id: 53,
  display_name: 'Squallin',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/richwild/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/nightlife',
  category: 'Counter-Strike: Global Offensive',
  followers: 61024,
  following: 78608 },
{ user_id: 54,
  display_name: 'secangkirtuak',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/sachacorazzi/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/people',
  category: 'Overwatch',
  followers: 70673,
  following: 11913 },
{ user_id: 55,
  display_name: 'leovartuli',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/guischmitt/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/fashion',
  category: 'Hearthstone',
  followers: 58068,
  following: 25877 },
{ user_id: 56,
  display_name: 'z_chezz30',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/prinzadi/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/transport',
  category: 'World of Warcraft',
  followers: 29304,
  following: 9044 },
{ user_id: 57,
  display_name: 'rockanhe23',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/weglov/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/nature',
  category: 'Fortnite',
  followers: 37347,
  following: 96062 },
{ user_id: 58,
  display_name: 'kingtheflexer',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/1markiz/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/city',
  category: 'Sea of Thieves',
  followers: 346,
  following: 93679 },
{ user_id: 59,
  display_name: 'h4y4m',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/mrebay007/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/abstract',
  category: 'Magic: The Gathering',
  followers: 26169,
  following: 86102 },
{ user_id: 60,
  display_name: 'macgyfereps11',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/allfordesign/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/cats',
  category: 'World of Warcraft',
  followers: 91192,
  following: 26719 },
{ user_id: 61,
  display_name: 'mentallyillanimefan',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/calebogden/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/nature',
  category: 'Call of Duty: Black Ops 4',
  followers: 91336,
  following: 25645 },
{ user_id: 62,
  display_name: 'pootch87',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/thierrykoblentz/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/abstract',
  category: 'Dota 2',
  followers: 93730,
  following: 4191 },
{ user_id: 63,
  display_name: 'talyahytvqyd',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/abdulhyeuk/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/cats',
  category: 'Left 4 Dead 2',
  followers: 94839,
  following: 37328 },
{ user_id: 64,
  display_name: 'cherryytzrty219',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/angelcolberg/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/animals',
  category: 'Dota 2',
  followers: 69709,
  following: 87553 },
{ user_id: 65,
  display_name: 'asasing2001',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/afusinatto/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/nature',
  category: 'Left 4 Dead 2',
  followers: 92145,
  following: 29238 },
{ user_id: 66,
  display_name: 'ghotreck',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/trueblood_33/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/sports',
  category: 'Hearthstone',
  followers: 64173,
  following: 23366 },
{ user_id: 67,
  display_name: 'JValvz',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/hafeeskhan/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/animals',
  category: 'Minecraft',
  followers: 55812,
  following: 92943 },
{ user_id: 68,
  display_name: 'eatmyasasrush',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/mahdif/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/nature',
  category: 'Grand Theft Auto V',
  followers: 18807,
  following: 39243 },
{ user_id: 69,
  display_name: 'angelikapxdqn',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/angelcreative/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/technics',
  category: 'Magic: The Gathering',
  followers: 28524,
  following: 27375 },
{ user_id: 70,
  display_name: 'sinfulkinslayer',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/samihah/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/animals',
  category: 'StarCraft II',
  followers: 64181,
  following: 25780 },
{ user_id: 71,
  display_name: 'Kanddie',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/colirpixoil/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/nightlife',
  category: 'Grand Theft Auto V',
  followers: 4834,
  following: 37111 },
{ user_id: 72,
  display_name: 'Phatedfool',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/digitalmaverick/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/city',
  category: 'League of Legends',
  followers: 58652,
  following: 75776 },
{ user_id: 73,
  display_name: 'Birdboss',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/longlivemyword/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/nature',
  category: 'Grand Theft Auto V',
  followers: 93715,
  following: 7075 },
{ user_id: 74,
  display_name: 'LethalNoxian',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/rohixx/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/sports',
  category: 'Portal 2',
  followers: 50639,
  following: 34732 },
{ user_id: 75,
  display_name: 'jendasgbcy4872',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/victorerixon/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/fashion',
  category: 'Left 4 Dead 2',
  followers: 77577,
  following: 18755 },
{ user_id: 76,
  display_name: 'fituhh',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/bluefx_/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/technics',
  category: 'Rocket League',
  followers: 18624,
  following: 18353 },
{ user_id: 77,
  display_name: 'CeesuBilu',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/yalozhkin/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/abstract',
  category: 'Rocket League',
  followers: 7343,
  following: 12389 },
{ user_id: 78,
  display_name: 'darelleihni',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/bungiwan/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/people',
  category: 'Minecraft',
  followers: 91471,
  following: 42472 },
{ user_id: 79,
  display_name: 'Rentroth81',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/felipecsl/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/fashion',
  category: 'Just Chatting',
  followers: 33174,
  following: 21962 },
{ user_id: 80,
  display_name: 'ophelielypo79',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/rodnylobos/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/food',
  category: 'Counter-Strike: Global Offensive',
  followers: 77048,
  following: 53313 },
{ user_id: 81,
  display_name: 'Mozarella82',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/itolmach/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/nightlife',
  category: 'Hearthstone',
  followers: 20122,
  following: 35780 },
{ user_id: 82,
  display_name: 'asd0917038100',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/adobi/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/nightlife',
  category: 'Overwatch',
  followers: 5039,
  following: 1127 },
{ user_id: 83,
  display_name: 'Wingadium',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/edobene/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/nature',
  category: 'Path of Exile',
  followers: 38596,
  following: 3981 },
{ user_id: 84,
  display_name: 'YamadaToko',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/rickdt/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/fashion',
  category: 'World of Warcraft',
  followers: 37312,
  following: 30010 },
{ user_id: 85,
  display_name: 'stolknekkern',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/jacobbennett/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/abstract',
  category: 'Grand Theft Auto V',
  followers: 76310,
  following: 39830 },
{ user_id: 86,
  display_name: 'Hellish_Doom',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/jlsolerdeltoro/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/fashion',
  category: 'Grand Theft Auto V',
  followers: 5323,
  following: 32316 },
{ user_id: 87,
  display_name: '412Menace',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/mrjamesnoble/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/cats',
  category: 'League of Legends',
  followers: 84943,
  following: 59435 },
{ user_id: 88,
  display_name: 'jessferl',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/bu7921/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/cats',
  category: 'PLAYERUNKNOWN\'S BATTLEGROUNDS',
  followers: 27302,
  following: 2736 },
{ user_id: 89,
  display_name: 'classickoo',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/mattsapii/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/animals',
  category: 'Magic: The Gathering',
  followers: 28012,
  following: 35936 },
{ user_id: 90,
  display_name: 'schliemann_twitch',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/waghner/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/food',
  category: 'Counter-Strike: Global Offensive',
  followers: 16755,
  following: 1541 },
{ user_id: 91,
  display_name: 'stepheniehzxd0718',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/eitarafa/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/nature',
  category: 'Portal 2',
  followers: 20427,
  following: 35266 },
{ user_id: 92,
  display_name: 'SoftForUbi',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/kostaspt/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/sports',
  category: 'World of Warcraft',
  followers: 77970,
  following: 1393 },
{ user_id: 93,
  display_name: 'rosannaftkml0',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/megdraws/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/technics',
  category: 'Rocket League',
  followers: 78276,
  following: 63622 },
{ user_id: 94,
  display_name: 'bernardingodzin',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/smenov/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/technics',
  category: 'Left 4 Dead 2',
  followers: 25853,
  following: 30563 },
{ user_id: 95,
  display_name: 'original_gangs',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/mattsapii/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/fashion',
  category: 'Just Chatting',
  followers: 41117,
  following: 27710 },
{ user_id: 96,
  display_name: 'kevinascostas',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/stefooo/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/business',
  category: 'Fortnite',
  followers: 41594,
  following: 17053 },
{ user_id: 97,
  display_name: 'datno',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/heyimjuani/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/food',
  category: 'PLAYERUNKNOWN\'S BATTLEGROUNDS',
  followers: 97368,
  following: 32627 },
{ user_id: 98,
  display_name: 'shakyamitabha',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/bolzanmarco/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/sports',
  category: 'Dota 2',
  followers: 16013,
  following: 54380 },
{ user_id: 99,
  display_name: 'dmitri_kovarskov',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/xalionmalik/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/food',
  category: 'Path of Exile',
  followers: 59911,
  following: 35386 },
{ user_id: 100,
  display_name: 'SupremeSpooky',
  logo: ' https://s3.amazonaws.com/uifaces/faces/twitter/madysondesigns/128.jpg',
  profile_image_url: ' http://lorempixel.com/640/480/animals',
  category: 'World of Warcraft',
  followers: 26506,
  following: 26451 }
];

module.exports = fakeData;